In [ ]:
import pandas as pd
import sqlite3
import os

DB_PATH = "practica_dml.db"

if os.path.exists(DB_PATH):
    os.remove(DB_PATH)
    print("Base de datos anterior eliminada")
else:
    print("No existía una base de datos anterior")

conn = sqlite3.connect("practica_dml.db")
cursor = conn.cursor()

Base de datos anterior eliminada

In [ ]:
cursor.execute ("""
CREATE TABLE vendedores (
id INTEGER PRIMARY KEY,
nombre TEXT NOT NULL,
ventas_totales REAL NOT NULL,
zona TEXT NOT NULL,
fecha_ingreso DATE NOT NULL
)
""")

conn.commit()

print("Base de datos y tabla creadas correctamente.")

Base de datos y tabla creadas correctamente.

In [ ]:
# Insertamos algunos registros en la base

cursor.execute("""
INSERT INTO vendedores (id, nombre, ventas_totales, zona, fecha_ingreso)
VALUES
    (1, 'Juan Perez', 8500, 'Norte', '2024-01-15'),
    (2, 'Maria Gomez', 9200, 'Sur', '2023-08-10'),
    (3, 'Carlos Lopez', 12500, 'Norte', '2022-05-20'),
    (4, 'Ana Martinez', 7000, 'Centro', '2024-03-12')
""")

conn.commit()

In [ ]:
#Con la base creada - ahora procedemos a crear los insert de nuevos vendedores

cursor.execute("""
INSERT INTO vendedores (nombre,ventas_totales,zona,fecha_ingreso)
VALUES
    ('Pedro Sanchez', 11000, 'Oeste', '2025-01-10'),
    ('Laura Diaz', 6000, 'Norte', '2025-02-15'),
    ('Sebastian Illbele', 150000.5, 'Centro' , '2025-08-27')
""")

conn.commit()

In [ ]:
df = pd.read_sql_query("""
SELECT * FROM vendedores"""
,conn)

df
#cursor.execute("""
#SELECT * FROM vendedores
#"""
#)

   id             nombre  ventas_totales    zona fecha_ingreso
0   1         Juan Perez          8500.0   Norte    2024-01-15
1   2        Maria Gomez          9200.0     Sur    2023-08-10
2   3       Carlos Lopez         12500.0   Norte    2022-05-20
3   4       Ana Martinez          7000.0  Centro    2024-03-12
4   5      Pedro Sanchez         11000.0   Oeste    2025-01-10
5   6         Laura Diaz          6000.0   Norte    2025-02-15
6   7  Sebastian Illbele        150000.5  Centro    2025-08-27

Imagina que el vendedor con id = 2 ha realizado una nueva venta. Actualiza su campo ventas_totales sumándole 500 unidades.
Reto: Cambia la zona a 'Internacional' para todos los vendedores que tengan más de 10,000 en ventas totales.

In [ ]:
# UPDATE de valores del id=2
#revisamos cuanto tiene hoy

ventas_antes = pd.read_sql_query("""
SELECT * FROM vendedores
WHERE id = 2
""",conn)

ventas_antes

cursor.execute("""
UPDATE vendedores
SET ventas_totales = ventas_totales + 500
WHERE id = 2
""")

conn.commit()


#revisamos cuanto le quedo despues
ventas_despues = pd.read_sql_query("""
SELECT * FROM vendedores
WHERE id = 2
""",conn)

display(ventas_antes)
display(ventas_despues)

   id       nombre  ventas_totales zona fecha_ingreso
0   2  Maria Gomez          9200.0  Sur    2023-08-10

   id       nombre  ventas_totales zona fecha_ingreso
0   2  Maria Gomez          9700.0  Sur    2023-08-10

Cambiar la zona a 'Internacional' para todos los vendedores que tengan más de 10.000 en ventas totales.

In [ ]:
cursor.execute("""
UPDATE vendedores
SET zona = 'Internacional'
WHERE ventas_totales > 10000
""")
conn.commit()

df = pd.read_sql_query("""
    SELECT id, nombre, ventas_totales, zona
    FROM vendedores
""", conn)

df

   id             nombre  ventas_totales           zona
0   1         Juan Perez          8500.0          Norte
1   2        Maria Gomez          9700.0            Sur
2   3       Carlos Lopez         12500.0  Internacional
3   4       Ana Martinez          7000.0         Centro
4   5      Pedro Sanchez         11000.0  Internacional
5   6         Laura Diaz          6000.0          Norte
6   7  Sebastian Illbele        150000.5  Internacional

Elimina a un vendedor de prueba que hayas creado, identificándolo por su id.

In [ ]:
cursor.execute("""
DELETE FROM vendedores
WHERE id=7
""")
conn.commit()

df = pd.read_sql_query("""
SELECT * FROM vendedores""",conn)

df

   id         nombre  ventas_totales           zona fecha_ingreso
0   1     Juan Perez          8500.0          Norte    2024-01-15
1   2    Maria Gomez          9700.0            Sur    2023-08-10
2   3   Carlos Lopez         12500.0  Internacional    2022-05-20
3   4   Ana Martinez          7000.0         Centro    2024-03-12
4   5  Pedro Sanchez         11000.0  Internacional    2025-01-10
5   6     Laura Diaz          6000.0          Norte    2025-02-15

In [61]:
from google.colab import files
files.download("practica_dml.db")